@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class Bishop
class Board
class CastlingMove
enum Color << enumeration >>
class Constants
class Coordinates
class EnPassantMove
class EndOfGameException
class GUIJavaFX
class Game
class GameController
enum GameEndCause << enumeration >>
class IllegalMoveException
class King
class Knight
interface Leaper << interface >>
class Main
class Move
class MoveFactory
class MoveHistory
class Pawn
class PawnPromotionException
class PawnPromotionMove
class Piece
enum PieceType << enumeration >>
class Player
interface Predicate3<T, U, V> << interface >>
interface Predicate4<T, U, V, Y> << interface >>
class Queen
class RegularMove
class RegularPiece
interface Rider << interface >>
class Rook
class RoyalPiece
class Square
enum SquareDanger << enumeration >>
enum SquareState << enumeration >>

Bishop                  -[#595959,dashed]->  Coordinates            : "«create»"
Bishop                  -[#000082,plain]-^  RegularPiece           
Board                   -[#595959,dashed]->  Bishop                 : "«create»"
Board                   -[#595959,dashed]->  Coordinates            : "«create»"
Board                  "1" *-[#595959,plain]-> "kingBlack\n1" King                   
Board                   -[#595959,dashed]->  King                   : "«create»"
Board                   -[#595959,dashed]->  Knight                 : "«create»"
Board                   -[#595959,dashed]->  Pawn                   : "«create»"
Board                   -[#595959,dashed]->  Queen                  : "«create»"
Board                   -[#595959,dashed]->  Rook                   : "«create»"
Board                  "1" *-[#595959,plain]-> "grid\n*" Square                 
Board                   -[#595959,dashed]->  Square                 : "«create»"
CastlingMove            -[#595959,dashed]->  IllegalMoveException   : "«create»"
CastlingMove            -[#000082,plain]-^  Move                   
CastlingMove           "1" *-[#595959,plain]-> "sourceKing\n1" Square                 
EnPassantMove           -[#595959,dashed]->  IllegalMoveException   : "«create»"
EnPassantMove           -[#000082,plain]-^  Move                   
EnPassantMove          "1" *-[#595959,plain]-> "takenPiece\n1" Piece                  
EnPassantMove          "1" *-[#595959,plain]-> "source\n1" Square                 
Game                    -[#000082,plain]-^  Board                  
Game                   "1" *-[#595959,plain]-> "board\n1" Board                  
Game                    -[#595959,dashed]->  Board                  : "«create»"
Game                    -[#595959,dashed]->  Coordinates            : "«create»"
Game                    -[#595959,dashed]->  EndOfGameException     : "«create»"
Game                   "1" *-[#595959,plain]-> "gameEndCause\n1" GameEndCause           
Game                   "1" *-[#595959,plain]-> "history\n1" MoveHistory            
Game                    -[#595959,dashed]->  MoveHistory            : "«create»"
Game                   "1" *-[#595959,plain]-> "player1\n1" Player                 
Game                    -[#595959,dashed]->  Player                 : "«create»"
GameController          -[#595959,dashed]->  Game                   : "«create»"
GameController         "1" *-[#595959,plain]-> "game\n1" Game                   
King                    -[#595959,dashed]->  Coordinates            : "«create»"
King                    -[#000082,plain]-^  RoyalPiece             
Knight                  -[#595959,dashed]->  Coordinates            : "«create»"
Knight                  -[#000082,plain]-^  RegularPiece           
Move                   "1" *-[#595959,plain]-> "player\n1" Player                 
MoveFactory             -[#595959,dashed]->  CastlingMove           : "«create»"
MoveFactory             -[#595959,dashed]->  Coordinates            : "«create»"
MoveFactory             -[#595959,dashed]->  EnPassantMove          : "«create»"
MoveFactory             -[#595959,dashed]->  PawnPromotionMove      : "«create»"
MoveFactory             -[#595959,dashed]->  RegularMove            : "«create»"
Pawn                    -[#595959,dashed]->  Coordinates            : "«create»"
Pawn                    -[#000082,plain]-^  RegularPiece           
PawnPromotionMove       -[#595959,dashed]->  Bishop                 : "«create»"
PawnPromotionMove       -[#595959,dashed]->  IllegalMoveException   : "«create»"
PawnPromotionMove       -[#595959,dashed]->  Knight                 : "«create»"
PawnPromotionMove       -[#000082,plain]-^  Move                   
PawnPromotionMove       -[#595959,dashed]->  PawnPromotionException : "«create»"
PawnPromotionMove      "1" *-[#595959,plain]-> "oldSelf\n1" Piece                  
PawnPromotionMove       -[#595959,dashed]->  Queen                  : "«create»"
PawnPromotionMove       -[#595959,dashed]->  Rook                   : "«create»"
PawnPromotionMove      "1" *-[#595959,plain]-> "source\n1" Square                 
Piece                  "1" *-[#595959,plain]-> "color\n1" Color                  
Piece                  "1" *-[#595959,plain]-> "legalPositions\n*" Coordinates            
Piece                  "1" *-[#595959,plain]-> "royalProtectorCausingPiece\n1" RegularPiece           
Player                 "1" *-[#595959,plain]-> "color\n1" Color                  
Player                 "1" *-[#595959,plain]-> "selection\n1" Square                 
Queen                   -[#595959,dashed]->  Coordinates            : "«create»"
Queen                   -[#000082,plain]-^  RegularPiece           
RegularMove             -[#595959,dashed]->  IllegalMoveException   : "«create»"
RegularMove             -[#000082,plain]-^  Move                   
RegularMove            "1" *-[#595959,plain]-> "takenPiece\n1" Piece                  
RegularMove            "1" *-[#595959,plain]-> "source\n1" Square                 
RegularPiece            -[#000082,plain]-^  Piece                  
Rider                   -[#008200,plain]-^  Leaper                 
Rook                    -[#595959,dashed]->  Coordinates            : "«create»"
Rook                    -[#000082,plain]-^  RegularPiece           
RoyalPiece              -[#000082,plain]-^  Piece                  
RoyalPiece             "1" *-[#595959,plain]-> "attackingPieces\n*" Piece                  
Square                 "1" *-[#595959,plain]-> "piece\n1" Piece                  
Square                 "1" *-[#595959,plain]-> "danger\n1" SquareDanger           
Square                 "1" *-[#595959,plain]-> "state\n1" SquareState            
@enduml
